name: Pull Request Checks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  pr-validation:
    name: PR Quality Checks (No Sonar)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Give gradlew execution permission
        run: chmod +x ./gradlew

      - name: Compile
        run: ./gradlew compileJava

      - name: Run Tests
        run: ./gradlew test

      - name: Build Jar
        run: ./gradlew bootJar
